
teep-message = $teep-message-type .within teep-message-framework

teep-message-framework = [
  type: $teep-type / $teep-type-extension,
  options: { * teep-option },
  * any; further elements, e.g., for data-item-requested
]

teep-option = (uint => any)

; messages defined below:
$teep-message-type /= query-request
$teep-message-type /= query-response
$teep-message-type /= update
$teep-message-type /= success
$teep-message-type /= error

; message type numbers, in one byte which could take a
; number from 0 to 23
$teep-type /= (0..23)
TEEP-TYPE-query-request = 1
TEEP-TYPE-query-response = 2
TEEP-TYPE-update = 3
TEEP-TYPE-success = 5
TEEP-TYPE-error = 6

query-request = [
  type: TEEP-TYPE-query-request,
  options: {
    ? token => bstr .size (8..64),
    ? supported-freshness-mechanisms => [ + $freshness-mechanism ],
    ? challenge => bstr .size (8..512),
    ? versions => [ + version ],
    ? attestation-payload-format => text,
    ? attestation-payload => bstr,
    ? suit-reports => [ + bstr .cbor SUIT_Report ],
    * $$query-request-extensions,
    * $$teep-option-extensions
  },
  supported-teep-cipher-suites: [ + $teep-cipher-suite ],
  supported-suit-cose-profiles: [ + $suit-cose-profile ],
  data-item-requested: uint .bits data-item-requested
]

version = uint .size 4
ext-info = uint .size 4

; data items as bitmaps
data-item-requested = &(
  attestation: 0,
  trusted-components: 1,
  extensions: 2,
  suit-reports: 3,
)

; teep-cipher-suites
$teep-cipher-suite /= teep-cipher-suite-sign1-ed25519
$teep-cipher-suite /= teep-cipher-suite-sign1-esp256

;The following two cipher suites have only a single operation each.
;Other cipher suites may be defined to have multiple operations.
;It is MANDATORY for TAM to support them, and OPTIONAL
;to support any additional ones that use COSE_Sign_Tagged, or other
;signing, encryption, or MAC algorithms.

teep-operation-sign1-ed25519 = [ cose-sign1, cose-alg-ed25519 ]
teep-operation-sign1-esp256  = [ cose-sign1, cose-alg-esp256 ]

teep-cipher-suite-sign1-ed25519 = [ teep-operation-sign1-ed25519 ]
teep-cipher-suite-sign1-esp256  = [ teep-operation-sign1-esp256 ]

;MANDATORY for TAM and TEEP Agent to support the following COSE
;operations, and OPTIONAL to support additional ones such as
;COSE_Sign_Tagged, COSE_Encrypt0_Tagged, etc.

cose-sign1 = 18      ; CoAP Content-Format value

;MANDATORY for TAM to support the following, and OPTIONAL to
;implement any additional algorithms from the IANA COSE Algorithms
;registry.

cose-alg-esp256  = -9   ; ECDSA using P-256 curve and SHA-256
cose-alg-ed25519 = -19  ; EdDSA using Ed25519 curve

; suit-cose-profile
$suit-cose-profile /= suit-sha256-esp256-ecdh-a128ctr
$suit-cose-profile /= suit-sha256-ed25519-ecdh-a128ctr
$suit-cose-profile /= suit-sha256-esp256-ecdh-a128gcm
$suit-cose-profile /= suit-sha256-ed25519-ecdh-chacha-poly

; freshness-mechanisms
FRESHNESS_NONCE = 0
FRESHNESS_TIMESTAMP = 1

$freshness-mechanism /= FRESHNESS_NONCE
$freshness-mechanism /= FRESHNESS_TIMESTAMP

query-response = [
  type: TEEP-TYPE-query-response,
  options: {
    ? token => bstr .size (8..64),
    ? selected-version => version,
    ? attestation-payload-format => text,
    ? attestation-payload => bstr,
    ? suit-reports => [ + bstr .cbor SUIT_Report ],
    ? tc-list => [ + system-property-claims ],
    ? requested-tc-list => [ + requested-tc-info ],
    ? unneeded-manifest-list => [ + SUIT_Component_Identifier ],
    ? ext-list => [ + ext-info ],
    * $$query-response-extensions,
    * $$teep-option-extensions
  }
]

requested-tc-info = {
  component-id => SUIT_Component_Identifier,
  ? tc-manifest-sequence-number => uint,
  ? have-binary => bool
}

update = [
  type: TEEP-TYPE-update,
  options: {
    ? token => bstr .size (8..64),
    ? unneeded-manifest-list => [ + SUIT_Component_Identifier ],
    ? manifest-list => [ + bstr .cbor SUIT_Envelope ],
    ? attestation-payload-format => text,
    ? attestation-payload => bstr,
    ? err-code => err-code-values,
    ? err-msg => text .size (1..128),
    ? err-lang => text .size (1..35),
    * $$update-extensions,
    * $$teep-option-extensions
  }
]

success = [
  type: TEEP-TYPE-success,
  options: {
    ? token => bstr .size (8..64),
    ? msg => text .size (1..128),
    ? suit-reports => [ + bstr .cbor SUIT_Report ],
    * $$success-extensions,
    * $$teep-option-extensions
  }
]

error = [
  type: TEEP-TYPE-error,
  options: {
     ? token => bstr .size (8..64),
     ? err-msg => text .size (1..128),
     ? err-lang => text .size (1..35),
     ? supported-teep-cipher-suites => [ + $teep-cipher-suite ],
     ? supported-freshness-mechanisms => [ + $freshness-mechanism ],
     ? supported-suit-cose-profiles => [ + $suit-cose-profile ],
     ? challenge => bstr .size (8..512),
     ? versions => [ + version ],
     ? suit-reports => [ + bstr .cbor SUIT_Report ],
     * $$error-extensions,
     * $$teep-option-extensions
  },
  err-code: err-code-values
]

; The err-code parameter
ERR_PERMANENT_ERROR = 1
ERR_UNSUPPORTED_EXTENSION = 2
ERR_UNSUPPORTED_FRESHNESS_MECHANISMS = 3
ERR_UNSUPPORTED_MSG_VERSION = 4
ERR_UNSUPPORTED_CIPHER_SUITES = 5
ERR_BAD_CERTIFICATE = 6
ERR_ATTESTATION_REQUIRED = 7
ERR_UNSUPPORTED_SUIT_REPORT = 8
ERR_CERTIFICATE_EXPIRED = 9
ERR_TEMPORARY_ERROR = 10
ERR_MANIFEST_PROCESSING_FAILED = 17

err-code-values = ERR_PERMANENT_ERROR
         / ERR_UNSUPPORTED_EXTENSION
         / ERR_UNSUPPORTED_FRESHNESS_MECHANISMS
         / ERR_UNSUPPORTED_MSG_VERSION
         / ERR_UNSUPPORTED_CIPHER_SUITES
         / ERR_BAD_CERTIFICATE
         / ERR_ATTESTATION_REQUIRED
         / ERR_UNSUPPORTED_SUIT_REPORT
         / ERR_CERTIFICATE_EXPIRED
         / ERR_TEMPORARY_ERROR
         / ERR_MANIFEST_PROCESSING_FAILED

; labels of mapkey for teep message parameters
supported-teep-cipher-suites = 1
challenge = 2
versions = 3
supported-suit-cose-profiles = 4
selected-version = 6
attestation-payload = 7
tc-list = 8
ext-list = 9
manifest-list = 10
msg = 11
err-msg = 12
attestation-payload-format = 13
requested-tc-list = 14
unneeded-manifest-list = 15
component-id = 16
tc-manifest-sequence-number = 17
have-binary = 18
suit-reports = 19
token = 20
supported-freshness-mechanisms = 21
err-lang = 22
err-code = 23
